### PR TITLE
add with_locale

### PR DESCRIPTION
**Pull request by mameier**
I18n, Globalize et al define with_locale. Add this functionality to FastGettext.

### CODE REVIEW

**Comment by grosser** [comment]
FYI ... added missing test and found a bug ... https://github.com/grosser/fast_gettext/commit/f4d4baadb8870f23cc41ec86ba97e384cd22e102

**Comment by grosser** [comment]
1.3.0

**Comment by mameier** [comment]
interesting, as set_locale is explicitly programmed to return the current locale.
thx for the fast pull

**Comment by basex** [comment]
I think this is quite useful. I added some documentation to the functionality here https://github.com/grosser/fast_gettext/pull/86

**Pull request merged**
