### PR TITLE
readme: actually use the translation

### PR DESCRIPTION
**Pull request by akimd**

### CODE REVIEW

**Comment by grosser** [comment]
hehe, good catch :)

**Comment by rgraff** [comment]
I think this is incorrect or at least confusing. If you're using the rake task to generate your pot files, you want to have both strings/keys defined separate, so you translate them separately,  and then use the % operator to interpolate them together.

**Comment by akimd** [comment]
> I think this is incorrect or at least confusing. If you're using the rake task to generate your pot files, you want to have both strings/keys defined separate, so you translate them separately, and then use the % operator to interpolate them together.

Sorry, I do not understand what you are saying.  The example explains how to "register" literal strings to enable i18n of computed values, but forgot to actually translate the computed value.

**Comment by rgraff** [comment]
My mistake. I misread the diff and thought you were removing the `_(status)` but in fact you were adding it. Yes, thank you for fixing this!

**Pull request merged**
