### PR TITLE
Add ruby 2.4 support in travis.

### PR DESCRIPTION
**Pull request by jrafanie**
Update to rails 4.2.8 or higher for ruby 2.4 support: https://github.com/rails/rails/pull/27473

### CODE REVIEW

**Comment by grosser** [comment]
thx! let me know when you get it green :)

**Comment by grosser** [comment]
can just exclude old rails versions vs 2.4

**Comment by jrafanie** [comment]
> grosser commented just now
> can just exclude old rails versions vs 2.4

I pushed changed to change the Gemfile to use rails 4.2.8, which supports ruby 2.4, I was able to bundle locally... let's see what happens

**Comment by jrafanie** [comment]
@grosser this is green now 🎉  ... let me know if it's acceptable.

**Comment by grosser** [comment]
thx!

**Pull request merged**
