### PR TITLE
drop rubies before 2.7

### PR DESCRIPTION
**Pull request by grosser**
everything before 3.0 failed because of sqlite3 vs nokogiri vs mini_*something dependency hell, so dropped them all ...

### CODE REVIEW

**Comment by renchap** [comment]
An issue here is that Rails / ActiveRecord do not support every Ruby version, so you might need to bump those as well.

**Comment by grosser** [comment]
yeah I'm trying to get at least 3.0 to work 🤞 ... then next step is bumping rails

**Comment by SPFZ** [comment]
This should have become version 3.0. It breakes many dependencies because it does not support ruby 2.7 anymore.

**Comment by grosser** [comment]
ah great ... I though rubygems had that figured out by now 😞 
... I can yank + bump

**Comment by grosser** [comment]
released as 3.0.0

**Pull request merged**
